import { notFound } from 'next/navigation';
import { BadgeCheck, MessageCircle } from 'lucide-react';
import { db } from '@aphrodite/database';
import { CharacterAvatar } from '@/components/characters/CharacterAvatar';
import { CharacterCategoryBadge } from '@/components/characters/CharacterCategoryBadge';
import { FavoriteButton } from '@/components/characters/FavoriteButton';
import { createConversationAction } from '../../actions';
import { requireUser } from '@/lib/require-auth';
export default async function CharacterPage({ params }: { params: Promise<{ slug: string }> }) { const user = await requireUser(); const character = await db.character.findFirst({ where: { slug: (await params).slug, isPublished: true } }); if (!character) notFound(); const favorite = await db.favorite.findUnique({ where: { userId_characterId: { userId: user.id, characterId: character.id } } }); return <div className="max-w-4xl"><div className={`h-52 rounded-3xl bg-gradient-to-br sm:h-64 ${character.coverUrl ?? character.avatarUrl}`} /><div className="relative mx-5 -mt-12 rounded-2xl border border-white/12 bg-[#17111d]/90 p-5 backdrop-blur sm:mx-8"><div className="flex flex-wrap items-end justify-between gap-5"><div className="flex items-end gap-4"><CharacterAvatar name={character.name} gradient={character.avatarUrl} size="lg" /><div><div className="flex items-center gap-2"><h1 className="text-3xl font-semibold tracking-[-0.05em]">{character.name}</h1><BadgeCheck className="size-5 text-fuchsia-200" /></div><p className="mt-1 text-white/50">{character.tagline}</p></div></div><FavoriteButton characterId={character.id} initialFavorite={Boolean(favorite)} /></div><div className="mt-6 flex flex-wrap gap-2"><CharacterCategoryBadge category={character.category} />{character.isFeatured && <span className="rounded-full bg-white/8 px-2.5 py-1 text-[10px] font-semibold tracking-wider text-white/65">FEATURED</span>}</div><p className="mt-6 max-w-2xl text-sm leading-7 text-white/63">{character.description}</p><div className="mt-7 rounded-2xl border border-fuchsia-200/12 bg-fuchsia-200/[0.055] p-4"><p className="text-xs font-semibold tracking-[0.15em] text-fuchsia-200/70">OPENING HELLO</p><p className="mt-2 text-sm italic leading-6 text-white/75">“{character.greeting}”</p></div><form action={createConversationAction} className="mt-7"><input type="hidden" name="characterId" value={character.id} /><button className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-[#170d20] hover:bg-fuchsia-100"><MessageCircle className="size-4" />Start chat</button></form></div></div>; }
